# Generated by Django 5.0.4 on 2024-04-30 04:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Sushi', 'Sushi'), ('Main', 'Main'), ('Small Dish', 'Small Dish'), ('Dessert', 'Dessert'), ('Soup', 'Soup'), ('Share', 'Share')], max_length=20)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('key', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='StoreProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_id', models.CharField(max_length=100)),
                ('store_url', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Manager', 'Manager'), ('Staff', 'Staff')], max_length=20)),
                ('username', models.CharField(max_length=100)),
                ('store_name', models.CharField(max_length=100)),
            ],
        ),
    ]
