# Generated by Django 5.0.4 on 2024-04-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='store_id',
            field=models.CharField(max_length=100),
        ),
    ]
