# Generated by Django 5.0.4 on 2024-04-30 14:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_store_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('store_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=100)),
                ('table_number', models.DecimalField(decimal_places=5, max_digits=10)),
                ('position_x', models.DecimalField(decimal_places=5, max_digits=10)),
                ('position_y', models.DecimalField(decimal_places=5, max_digits=10)),
                ('width', models.DecimalField(decimal_places=5, max_digits=10)),
                ('height', models.DecimalField(decimal_places=5, max_digits=10)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='api.layout')),
            ],
        ),
    ]
