# Generated by Django 5.0.4 on 2024-05-11 11:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_table_table_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Cooking', 'Cooking'), ('Ready to serve', 'Ready to serve')], max_length=20)),
                ('order_time', models.TimeField()),
                ('table_number', models.IntegerField()),
                ('product_count', models.IntegerField()),
                ('completed_order_count', models.IntegerField()),
                ('order_type', models.CharField(choices=[('Dine in', 'Dine in'), ('Takeaway', 'Takeaway')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('menu_name', models.CharField(max_length=100)),
                ('menu_image', models.ImageField(upload_to='')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='api.product')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='api.order')),
            ],
        ),
    ]
