# Generated by Django 5.0.4 on 2024-05-11 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_alter_table_table_number_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='store_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='api.store'),
            preserve_default=False,
        ),
    ]
