# Generated by Django 5.0.4 on 2024-05-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completeStatus',
            field=models.BooleanField(default=False),
        ),
    ]
