# Generated by Django 5.0.4 on 2024-05-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_order_completestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='complete_status',
            field=models.BooleanField(default=False),
        ),
    ]
